name: IceBoatTimer
version: '1.0-SNAPSHOT'
main: cn.xor7.xiaohei.iceBoatTimer.IceBoatTimer
api-version: '1.20'
dependencies:
  server:
    ParticleLib:
      load: BEFORE
      required: true
      join-classpath: true